# Generated by Django 5.0.6 on 2026-02-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text="Bootstrap icon class (e.g., 'bi-mic')", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='musicians/')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Usuário')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('skills', models.ManyToManyField(blank=True, to='core.skill', verbose_name='Habilidades')),
            ],
        ),
    ]
