# Generated by Django 5.0.6 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_setlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Foto/Banner'),
        ),
    ]
