# Generated by Django 5.0.6 on 2026-02-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('photo', models.ImageField(upload_to='institutions/', verbose_name='Foto/Logo')),
                ('responsible_name', models.CharField(max_length=150, verbose_name='Responsável')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='É Líder?'),
        ),
        migrations.AddField(
            model_name='musician',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicians', to='core.institution', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='core.institution', verbose_name='Instituição'),
        ),
    ]
