# Generated by Django 5.0.6 on 2026-02-07 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_institution_musician_is_leader_musician_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_api_key', models.CharField(blank=True, max_length=300, null=True, verbose_name='Google API Key (YouTube)')),
                ('spotify_client_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='Spotify Client ID')),
                ('spotify_client_secret', models.CharField(blank=True, max_length=300, null=True, verbose_name='Spotify Client Secret')),
                ('deezer_enabled', models.BooleanField(default=True, verbose_name='Deezer Habilitado')),
                ('cifra_enabled', models.BooleanField(default=True, verbose_name='Cifra Club Habilitado')),
                ('letras_enabled', models.BooleanField(default=True, verbose_name='Letras.mus.br Habilitado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de API',
                'verbose_name_plural': 'Configurações de APIs',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('artist', models.CharField(max_length=300, verbose_name='Artista')),
                ('key', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tom')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('spotify_url', models.URLField(blank=True, null=True, verbose_name='Link Spotify')),
                ('deezer_url', models.URLField(blank=True, null=True, verbose_name='Link Deezer')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Link YouTube')),
                ('cifra_url', models.URLField(blank=True, null=True, verbose_name='Link Cifra Club')),
                ('letras_url', models.URLField(blank=True, null=True, unique=True, verbose_name='Link Letras.mus.br')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_musics', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'ordering': ['title', 'artist'],
            },
        ),
    ]
