# Generated by Django 5.0.6 on 2026-02-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apiconfig_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Música',
                'verbose_name_plural': 'Categorias de Músicas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='core.musiccategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='MusicSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.musiccategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria de Música',
                'verbose_name_plural': 'Subcategorias de Músicas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='music',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='core.musicsubcategory', verbose_name='Subcategoria'),
        ),
    ]
