# Generated by Django 5.0.6 on 2026-02-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_musiccategory_music_category_musicsubcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6F2682', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#36C2D7', max_length=7, verbose_name='Cor Secundária')),
                ('error_color', models.CharField(default='#F25F5C', max_length=7, verbose_name='Cor de Erro')),
                ('success_color', models.CharField(default='#A0D440', max_length=7, verbose_name='Cor de Sucesso')),
                ('warning_color', models.CharField(default='#FFB337', max_length=7, verbose_name='Cor de Alerta')),
                ('sidebar_bg', models.CharField(default='#D2D9E8', max_length=7, verbose_name='Fundo da Sidebar')),
                ('main_bg', models.CharField(default='#FCFCFC', max_length=7, verbose_name='Fundo Principal')),
                ('gradient_start', models.CharField(default='#6F2682', max_length=7, verbose_name='Início do Gradiente')),
                ('gradient_end', models.CharField(default='#B469FB', max_length=7, verbose_name='Fim do Gradiente')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Tema',
                'verbose_name_plural': 'Configurações de Temas',
            },
        ),
    ]
