# Generated by Django 5.0.6 on 2026-02-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_themeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
