# Generated by Django 5.0.6 on 2026-02-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_musician_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='body_text_color',
            field=models.CharField(default='#212529', max_length=7, verbose_name='Cor do Texto'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='border_color',
            field=models.CharField(default='#dee2e6', max_length=7, verbose_name='Cor da Borda'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='card_bg',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Fundo dos Cards'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='sidebar_text_color',
            field=models.CharField(default='#555555', max_length=7, verbose_name='Cor do Texto da Sidebar'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='subtitle_color',
            field=models.CharField(default='#495057', max_length=7, verbose_name='Cor do Subtítulo'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='title_color',
            field=models.CharField(default='#212529', max_length=7, verbose_name='Cor do Título'),
        ),
    ]
