# Generated by Django 5.2.6 on 2025-09-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0009_remove_profile_birth_date_remove_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
